theme="material-design"
baseurl = "https://alangley345.github.io"
languageCode = "en-us"
title = "Welcome"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
disqusShortname = "Your Disqus Name" # optional
copyright = "© 2021 Copyright Text"

[params]
  description = "A Place for Rambling" # optional
  github      = "alangley345" # optional
  linkedin    = "alangley345" # optional
  headerCover = "images/headerCover.png" # optional
  footerCover = "images/footerCover.png" # optional
  googleAnalyticsUserID = "Your Analytics User Id" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional